File_Name: final_data.csv

columns:
  date: object
  store_nbr: int64
  family: object
  sales: float64
  onpromotion: int64
  holiday_type: object
  locale: object
  locale_name: object
  description: object
  transferred: bool
  dcoilwtico: float64
  city: object
  state: object
  store_type: object
  cluster: int64
  transactions: float64
  

numerical_columns:
- store_nbr
- sales
- onpromotion
- oil_price
- cluster
- transactions 

numerical_columns_without_target:
- store_nbr
- onpromotion
- oil_price
- cluster
- transactions 


categorical_columns:
- family
- holiday_type
- locale
- locale_name
- description
- city
- state
- store_type
- transferred

date_columns:
- date

drop_columns:
- transferred
- locale
- locale_name
- description
- city
- state

label_encoder_columns:
- holiday_type
- store_type

target_column:
- sales