time_model_file_name: grouped_data.csv
drop_columns:
- family
- holiday_type
- locale
- locale_name
- description
- city
- state
- cluster
- transactions
group_columns:
- date
sum_columns:
- onpromotion
- holiday_type
- sales
- store_type
- store_nbr
mean_columns:
- oil_price
label_encode:
- holiday_type
target_column:
- sales
exog_columns:
- onpromotion
- holiday_type
- store_type
- store_nbr

