PIKLE_FOLDER_NAME_KEY='Time_Prediction_Files'

# Time Data Transformation related variables
TIME_DATA_TRANSFORMATION_CONFIG_KEY = "time_data_transformation_config"
TIME_DATA_TRANSFORMATION_ARTIFACT_DIR = "time_data_transformation"
TIME_DATA_TRANSFORMATION_DIR_NAME_KEY = "time_transformed_dir"
TIME_DATA_TRANSFORMATION_TRAIN_DIR_NAME_KEY = "time_transformed_train_dir"
TIME_DATA_TRANSFORMATION_TEST_DIR_NAME_KEY = "time_transformed_test_dir"
TIME_DATA_TRANSFORMATION_PREPROCESSING_DIR_KEY = "time_preprocessing_dir"
TIME_DATA_TRANSFORMATION_PREPROCESSING_FILE_NAME_KEY = "time_preprocessed_object_file_name"
TIME_DATA_TRANSFORMATION_FEATURE_ENGINEERING_FILE_NAME_KEY ="time_feature_engineering_object_file_name"